name: Speed Comparison

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  run-time-benchmarks:
    runs-on: ubuntu-latest
    concurrency: 
      group: "speed-comparison-run-time-${{github.ref_name}}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Benchmark
        run: sudo -E dotnet run -c Release --framework net9.0 --filter '*' --join
        working-directory: "Benchmark"

      - name: Upload Markdown
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}_markdown_run_time
          path: |
            **/BenchmarkDotNet.Artifacts/**